name: quiz-app
region: nyc
services:
- name: web-service
  image:
    registry_type: DOCKER_HUB
    registry: dockerhub
    tag: latest
  environment_slug: python
  http_port: 3000
  routes:
    - path: /
  instance_size_slug: basic-xxs
  instance_count: 1

  

