name: quiz_app
region: nyc

services:
- environment_slug: python
  image:
    registry: dockerhub
    username: ${{ secrets.DOCKER_USERNAME }}
    name: quiz_app_final
    tag: latest
  name: website
  instance_count: 1
  http_port: 3000
  routes:
    - path: /


  

