name: quiz-app
region: nyc
services:
- name: web-service
  image:
    registry_type: DOCKER_HUB
    registry: minjae07206
    repository: quiz_app_final
    tag: latest
  environment_slug: python
  http_port: 3000
  routes:
    - path: /
  instance_size_slug: basic-xxs
  instance_count: 1

  envs:
  - key: MONGO_DBNAME
    scope: RUN_AND_BUILD_TIME
    type: GENERAL
    value: Cluser0
  - key: FLASK_APP
    scope: RUN_AND_BUILD_TIME
    type: GENERAL
    value: app.py
  - key: GITHUB_REPO
    scope: RUN_AND_BUILD_TIME
    type: GENERAL
    value: https://github.com/software-students-spring2024/5-final-project-spring-2024-se-2pm-final

  

