services:
- image:
    registry_type: DOCKER_HUB
    registry: dockerhub
    repository: minjae07206/quiz_app_final
    username: ${{ secrets.DOCKER_USERNAME }}
    tag: latest
  instance_count: 1
  http_port: 3000
  routes:
    - path: /

  

