name: Web-app CI
on: [push, pull_request]

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # update version(s) as needed

      - name: Install dependencies
        run: |
          cd quiz_app
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv sync --dev --python $(which python)
          pipenv shell --fancy --python $(which python)

      - name: Test with pytest
        run: |
          cd quiz_app
          pipenv run pytest test_app.py
  build-and-publish:
    needs: unit-testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          cd quiz_app
          docker build -t quiz_app_image .
          
      
